### PR TITLE
Update according to cookiecutter template and add test suite.

### PR DESCRIPTION
**Pull request by henri-hulski**
See #434.
I also fix the tests and add a full test suite for the REST API.

@faassen 
Here I make a pull request as this is the first one and I added the test suite adopted from morepath_cerebral_todomvc,
So please look at it.
If it's ok the next ones I will make in the trunk.

### CODE REVIEW

**Comment by henri-hulski** [comment]
I think it's also ready for release.

**Comment by henri-hulski** [comment]
@faassen 
Wait a moment with merging.

I just found out when running the app you see nothing in the browser.
You can query the API also in the browser but redux is not rendering.
So I have to check, what I messed up.

**Comment by henri-hulski** [comment]
Evereything is ok. I just had to refresh the browser cache as I was running another app before on this port. :+1:

**Comment by henri-hulski** [comment]
BTW I also added a LICENSE file, which I took from Morepath.
I hope this is ok.

**Comment by henri-hulski** [comment]
I forget to add the Github reference to the README.
Don't you think, it would be enough to add a url keyword to setup.py?
It will then show up as **Home Page** in PyPI.

**Comment by faassen** [comment]
Looks good! 

I noticed you say it works with Python 3 in `setup.py`, but we have no tox set up I'm going to merge anyway, but it's something to consider for the future.

**Pull request merged**
